### ISSUE TITLE
1.4.4.py

### ISSUE THREAD

**Issue by jsqlzy** [qiyeboy/SpiderBook#1]
#实现第六步：添加任务
for url in ["ImageUrl_"+str(i) for i in range(10)]:
    print 'put task %s ...' %url
    task.put(url)

有个地方 给你修正一下   ["ImageUrl_"+str(i) for i in range(10)

**Comment by qiyeboy** [comment]
谢谢，已经在勘误表中修正，windows版不受影响 @jsqlzy
