### ISSUE TITLE
firebug的console无法使用

### ISSUE THREAD

**Issue by lihp11** [qiyeboy/SpiderBook#10]
书上86页推荐的firebug好像在新的firefox上无法显示console，换成旧版的firefox（知乎上有人推荐采用v49.0.2）也不行~
![image](https://user-images.githubusercontent.com/15975692/27855678-f4c9a216-619d-11e7-845a-8c791170ae80.png)

**Comment by qiyeboy** [comment]
我使用的版本为Firefox v49,Firebug v2.0.9
