### ISSUE TITLE
关于第17章scrapy分布式爬虫运行代码是遇到的问题

### ISSUE THREAD

**Issue by Rayzian** [qiyeboy/SpiderBook#12]
作者你好，我在运行你的GitHub ch17的代码是遇到下面的情况：
使用scrapy crawl yunqi.qq.com时，爬虫能Get到start_urls，但是没有进行解析，爬虫就结束关闭了，如图：

![default](https://user-images.githubusercontent.com/29925823/27895859-8d505818-6248-11e7-9c31-8a9bb6fc1cd3.png)

我打算用scrapy shell查看被处理网页的response，但是报错了，如图：
![default](https://user-images.githubusercontent.com/29925823/27895976-781b61c6-6249-11e7-9bca-64b20533d57b.png)

因为我是才开始学习和使用scrapy，所以遇到这个问题不知道该从哪里开始定位，请作者指点下，谢谢

代码运行的环境：ubuntu17.04，运行代码前已启动redis服务和mongodb服务器

**Comment by qiyeboy** [comment]
shell虽然是全局命令，但是在项目根目录下启动时会受项目设置的影响，会报错，你切换到其他目录再运行就没问题了
