### ISSUE TITLE
DynamicSpider

### ISSUE THREAD

**Issue by ldkgit** [qiyeboy/SpiderBook#13]
这个爬虫的比网页显示的数据少，存到sqlite里的也少，运行后'NoneType' object has no attribute 'get' http://service.library.mtime.com/Movie.api?Ajax_CallBack=true&Ajax_CallBackType=Mtime.Library.Services&Ajax_CallBackMethod=GetMovieOverviewRating&Ajax_CrossDomain=1&Ajax_RequestUrl=http://movie.mtime.com/247097/&t=201707072006523282&Ajax_CallBackArgument0=247097 {u'value': {u'userLastComment': u'', u'releaseType': 1, u'isRelease': True, u'tweetId': 0, u'movieRating': {u'TitleEn': u'', u'RPictureFinal': 0, u'AttitudeCount': 22, u'MovieId': 247097, u'TitleCn': u'', u'RShowFinal': 0, u'RDirectorFinal': 0, u'EnterTime': 0, u'RTotalFinal': 0, u'UserId': 0, u'ROtherFinal': 0, u'JustTotal': 0, u'Year': u'', u'RatingFinal': -1, u'RatingCount': 0, u'RStoryFinal': 0, u'IP': 0, u'Usercount': 23}, u'movieTitle': u'\u649e\u90aa31\u53f7', u'userLastCommentUrl': u''}, u'error': None}
有这种日志

**Comment by qiyeboy** [comment]
这里的代码只是一个demo,教你怎么爬取ajax,由于不同的电影返回的数据，有一些字段没有，会报错，你加上异常处理就行了
