### ISSUE TITLE
有个地方给你指正一下？

### ISSUE THREAD

**Issue by jsqlzy** [qiyeboy/SpiderBook#15]
第６章　DataOutput.py　生成普通文档是没问题的，但生成html文档，当用火狐浏览器打开时会出现乱码，所以需要加入下面这条语句<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />具体如下

　　　　　fout.write("<html>")	
		fout.write('<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />')
		fout.write("<body>")

**Comment by qiyeboy** [comment]
是有问题，但不能这么解决，在头部添加fout.write("<head> <meta charset='utf-8'/></head>")即可，当时使用谷歌可以自动识别编码，当然你可以在火狐中选择不同的编码显示
