### ISSUE TITLE
请教问题？

### ISSUE THREAD

**Issue by jsqlzy** [qiyeboy/SpiderBook#19]
你好：
第９章　动态网站抓取　获取时光网例子　　网页解析类的代码 HtmlParser 中
pattern = re.compile(r'(http://movie.mtime.com/(\d+)/)')　此处　\d＋加上了括号　(\d+)/)　
打印如下：　我不理解为何会出现数字 u'10910'被单独提取出来．
[(u'http://movie.mtime.com/10910/', u'10910'), (u'http://movie.mtime.com/211901/', u'211901'), (u'http://movie.mtime.com/211901/', u'211901'),　　谢谢解释．请问这是正则的一个用法么？

**Comment by qiyeboy** [comment]
正则表达式中的分组，我在正则表达式中讲了

**Comment by jsqlzy** [comment]
谢谢
