### ISSUE TITLE
书籍错误

### ISSUE THREAD

**Issue by lg-Cat73** [qiyeboy/SpiderBook#2]
昨天(2017年6月21日)在京东买的电子版。

* 8.2.3.2 sqlite3模块使用connect方法打开数据库
  这儿是在讲 mysql 数据库。。。

之前还看到不少错误，不过都没来提，以后慢慢提吧。。
话说京东的书修订了会更新么。。。

**Comment by qiyeboy** [comment]
@lg-Cat73 首先说一下京东电子版的排版有问题，很多内容丢失了或者添加了，有朋友在博客中也提到，和实体书不一样，尴尬，所以提醒大家买实体书。你提到的这个问题我查看了实体书，应该是当时笔误了，没发现。当再次印刷的时候错误就没了，再次感谢你的支持。

**Comment by lg-Cat73** [comment]
感觉看着问题不打 0.0
毕竟该缩进的地方前面几乎都有冒号 0.0

**Comment by qiyeboy** [comment]
你可以看一下讲正则表达式的一章，关于零宽断言的，电子书错的太多了，实体书上没有问题
![image](https://user-images.githubusercontent.com/8142734/27423765-4a757a48-5765-11e7-9b2e-ec93fb2c61dd.png)

**Comment by qiyeboy** [comment]
不知道他们电子书怎么弄得

**Comment by lg-Cat73** [comment]
正则的技能点本来就差点点满了。。我是直接跳过去的。。

**Comment by qiyeboy** [comment]
@lg-Cat73

**Comment by lg-Cat73** [comment]
0.0 我先自己多折腾会 凑巧看到再提 0.0
之前看到的都忘了在哪惹 0.0
