### ISSUE TITLE
配置环境

### ISSUE THREAD

**Issue by zola910** [qiyeboy/SpiderBook#20]
您好，我最近在用这本书进行爬虫的学习，因为没接触过爬虫，我想问下您书中提到的两个IDE是必须要配置的吗，我只用python自带的shell 进行编写可以的吗

**Comment by jsqlzy** [comment]
自带的会很麻烦　　提高效率需要ＩＤＥ

**Comment by qiyeboy** [comment]
当然可以用shell,但是用IDE会很方便 @zola910
