### ISSUE TITLE
怎么快速去掉引号？

### ISSUE THREAD

**Issue by jiushizheyang** [qiyeboy/SpiderBook#24]
好多代码都是用
'''

'''
包围起来的，怎么快速去掉这些符号？

**Comment by qiyeboy** [comment]
我使用的这个目的是为了分隔不同章节的代码，因为有的章里可能没有成型的工程，只是一些代码片段，小例子，所以都集成到一个py文件了，你学到哪个例子，就去掉哪个''' '''就可以直接运行了，你把一个py文件中的所有''' '''去掉没有意义呀，这样反而运行不了

**Comment by jiushizheyang** [comment]
我以为你频繁使用''' '''是有快捷键的
