### ISSUE TITLE
第六章 DataOutput

### ISSUE THREAD

**Issue by acutesun** [qiyeboy/SpiderBook#25]
在对数据进行遍历的时候删除元素会导致元素跟踪丢失， 使用切片解决
        for data in self.datas[:]:
            count += 1
            fout.write("<tr>")
            fout.write("<td>%s</td>" % data['url'])
            fout.write("<td>%s</td>" % data['title'])
            fout.write("<td>%s</td>" % data['summary'])
            fout.write("</tr>")
            self.datas.remove(data)

**Comment by Bruceelv** [comment]
我也发现了这个问题，我承认这个问题让我找了一个上午，让大神们见笑了。开始我是这么解决的：

        for j in range(len(self.datas)):
            for data in self.datas:
                #存储方式为一行三列的形式
                fout.write('<tr>')
                print('b',data['title'])
                print('b',data['summary'])
                fout.write("<td>%s</td>" % data['url'])
                fout.write('<td>%s</td>'%data['title'])
                fout.write('<td>%s</td>'%data['summary'])
                fout.write('</tr>')
                self.datas.remove(data)

试了一下你的这个方法（貌似count +=1是做测试用的吧），果然是比我的方法高明。受教了！

**Comment by kgdwhsk** [comment]
直接去掉self.datas.remove(data)不行吗
`        for data in self.datas:
            fout.write("<tr>")
            # fout.write("<td><a href=" + data['url'] + ">" + data['url'] + "</a></td>")
            fout.write('<td><a href=%s target="_blank">%s</a></td>' % (data['url'], data['url']))
            fout.write("<td>%s</td>" % data['title'])
            fout.write("<td>%s</td>" % data['summary'])
            fout.write("</tr>")
            # self.datas.remove(data) # 修改列表会造成遍历漏网之鱼`

**Comment by qiyeboy** [comment]
请原谅，当时可能脑子抽风了，添加了这么一句，去掉self.datas.remove(data)即可 @kgdwhsk
