### ISSUE TITLE
P146 运行SpiderMan.py出错

### ISSUE THREAD

**Issue by laoding2016** [qiyeboy/SpiderBook#28]
运行SpiderMan.py报错：
self.manager.add_new_url(root_url)
AttributeError: 'SpiderMan' object has no attribute 'manager'

用的py3
代码如下：
![image](https://user-images.githubusercontent.com/22270719/28784348-c3032d62-7645-11e7-9d8b-b6543d87040d.png)

**Comment by JinLiangYang** [comment]
检查下import，是不是没有导入
![image](https://user-images.githubusercontent.com/18231923/28955067-07966214-7916-11e7-84a5-8bd4f358c159.png)
