### ISSUE TITLE
关于第四章

### ISSUE THREAD

**Issue by zola910** [qiyeboy/SpiderBook#29]
关于第四章有个代码如下
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html14/strict.dtd>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>FireFox 测试</title>
</head>
<body>
<script type="text/javascript">
var a="python";
var b="爬虫开发";
document.write(a,b);
console.log(a,b);
console.debug(a+b);
console.error(a+b);
console.info(a+b);
console.warn(a+b);
</script>
</body>
</html>
我照书中所写的，但是显示只显示了一行‘’python 爬虫开发‘’，并且没有其他显示，不像书中显示的有五行‘python 爬虫开发’

![eee](https://user-images.githubusercontent.com/27477864/28996318-89beb0dc-7a30-11e7-84ef-a0f742aa7553.jpg)
![12](https://user-images.githubusercontent.com/27477864/28996326-f549ee5c-7a30-11e7-8ef8-f6e9d06d8cba.jpg)
![3](https://user-images.githubusercontent.com/27477864/28996327-fab9db54-7a30-11e7-8901-4d68bb4524e2.jpg)

第三张是我打开网页显示的，与书中不一样，只显示了一行

**Comment by qiyeboy** [comment]
和Firefox版本有关，我用的是v49
