### ISSUE TITLE
请看14章知乎。

### ISSUE THREAD

**Issue by Lv-7** [qiyeboy/SpiderBook#32]
服务器设置了aliyungf_tc'、r_cap_id等参数的值，这些通过设置COOKIES_ENABLED = True
COOKIES_DEBUG = True是可以获取得到的，但是传递cookie的时候还有__utma、__utmc、__utmz、__utmb的值，请教下这个要怎么办，原书中的代码根本登录不上，第一次登录是要验证码的。

**Comment by callme9527** [comment]
把所有的cookie都清除之后，再登录抓包时cookie是没有__utma、__utmc、__utmz、__utmb这些的。构造好验证码post后显示502，500是什么原因

**Comment by Lv-7** [comment]
有的呀，ut开头的这几个都一直存在的，分析用户访问习惯的，好像可以不传的。验证码始终过期，登陆不了。

**Comment by qiyeboy** [comment]
尴尬，当时写这个项目的时候，没有验证码，很容易登录，给你们推荐个项目https://github.com/qiyeboy/fuck-login，应该可以解决你们的问题 @Lv-7 @callme9527
