### ISSUE TITLE
第12章爬取文章摘要的XPath需更改

### ISSUE THREAD

**Issue by PeterZengMing** [qiyeboy/SpiderBook#35]
第12章cnblogSpider/cnblogSpider/spiders/cnblogs_spider.py文件的第25行目前为：
` content = paper.xpath(".//*[@class='postCon']/a/text()").extract()[0]`
但我运行时抓不到任何东西，将其中XPath表达式改为：
`.//*[@class='postCon']/div/text()`
后即可运行。似乎是因为该网页的源代码有改动：
`<div class="postCon"><div class="c_b_p_desc">摘要: 熊猫烧香病毒在当年可是火的一塌糊涂，感染非常迅速，算是病毒史上比较经典的案例。不过已经比`

**Comment by qiyeboy** [comment]
感谢，已经修正
