### ISSUE TITLE
UserWarning: You provided Unicode markup but also provided a value for from_encoding. 

### ISSUE THREAD

**Issue by CHEYULIU** [qiyeboy/SpiderBook#37]
关于第六章爬取网络爬虫词条的语法报错
我将你写的代码以及按照github中的勘误修正你书中的错误后，执行后发现：
UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
然后我百度了一下，有人说将soup = BeautifulSoup(html_cont,'html.parser',from_encoding='utf-8')中的
**from_encoding='utf-8**去掉，但仍然还是报错！
爬了你的部落格什么的都没有相关问题，我已经遇到好几次这个问题，准备丢书了！

**Comment by qiyeboy** [comment]
这不是错误，这是warning，不影响数据提取，不要轻言放弃。如果是报错的话，就绝对不是这个问题，你可以将问题图贴出来，大家一起解决，不要放弃 @CHEYULIU

**Comment by CHEYULIU** [comment]
但是爬取后的HTML档案仍然没有数据，
![default](https://user-images.githubusercontent.com/31812232/30248057-85eeb77e-9653-11e7-97c9-51936f423700.png)
@qiyeboy

**Comment by qiyeboy** [comment]
你贴一下关键的代码，也就是爬取的部分，数据抽取的部分 @CHEYULIU

**Comment by CHEYULIU** [comment]
![default](https://user-images.githubusercontent.com/31812232/30248140-02f73ec0-9655-11e7-8e17-7b468aea9597.png)
![default](https://user-images.githubusercontent.com/31812232/30248153-1b544058-9655-11e7-99ed-d695e12ee44c.png)

**Comment by qiyeboy** [comment]
你的解析规则？ @CHEYULIU

**Comment by CHEYULIU** [comment]
你是说附上HTML解析的代码么？
@qiyeboy

**Comment by qiyeboy** [comment]
对的

**Comment by CHEYULIU** [comment]
好的
![default](https://user-images.githubusercontent.com/31812232/30248190-b170ba12-9655-11e7-8628-5725f3bccf7d.png)
![default](https://user-images.githubusercontent.com/31812232/30248197-cb9c3984-9655-11e7-9f02-76140814618a.png)

**Comment by qiyeboy** [comment]
我用的也是github中的源码 ，一切正常，可以抓取
![image](https://user-images.githubusercontent.com/8142734/30248262-e066e0ac-9656-11e7-8db4-a11fda10140a.png)

**Comment by qiyeboy** [comment]
我看你进行了修改，应该是改的某个地方出错 @CHEYULIU

**Comment by CHEYULIU** [comment]
我其实没有什么修改耶，我一开始是先按书上的代码打进去，然后看你的github上说的进行勘误，剩下的就是'''.... '''里面中文换英文而已！

@qiyeboy

**Comment by qiyeboy** [comment]
这样，你把代码发到我邮箱，邮箱在github中，我给你看一下，个人感觉是你代码打的有问题 @CHEYULIU

**Comment by CHEYULIU** [comment]
好的！
麻烦你了！
@qiyeboy

**Comment by CHEYULIU** [comment]
作者你好，我刚刚试了一下github上的源码，发现可以运行，然后我又再检查一次我写的代码，发现还是没有问题，后来我发现，我将除了‘爬虫调度器’这块代码以外的4个模块都发布了，我重新将这五个模块直接放到一个package里后执行就可以正常执行了！
我想请问一下，我以为要将模块发布出去后，才能在另一个模块中调用！今天是我第一次发现原来放在同一个package里的模块都可以互相调用，这是为什么？
谢谢~
@qiyeboy

**Comment by qiyeboy** [comment]
原本就可以呀
