### ISSUE TITLE
第一章，第17页，关于join方法的建议

### ISSUE THREAD

**Issue by Dang9527** [qiyeboy/SpiderBook#43]
@qiyeboy 您好，
join方法阻塞运行直至该进程结束，如果需要等待所有子进程结束，建议针对每个进程调用该方法。

原书代码：
def run_proc(name):

    print 'Child process %s (%s) Running...' % (name, os.getpid())

if __name__ == '__main__':

    print 'Parent process %s.' % os.getpid()

    for i in range(5):

        p = Process(target=run_proc, args=(str(i),))

        print 'Process will start.'

        p.start()

    p.join()

    print 'Process end.'

建议将子进程规整入列表，以方便使用迭代处理每个进程，并“同步”每个进程，确保父进程在所有子进程结束后继续。修改如下：
def run_proc(name):

    print 'Child process %s (%s) Running...' % (name, os.getpid())

if __name__ == '__main__':

    print 'Parent process %s.' % os.getpid()
    p=[]
    for i in range(5):

        p.append(Process(target=run_proc, args=(str(i),)))

        print 'Process will start.'

        p[i].start()

利用进程列表，确保子进程全部结束后父进程再继续

     for process in p:
           process.join()

     print 'Process end.'

**Comment by bihuchao** [comment]
也看到这个了，原来的语句可能对初学者造成误解。

**Comment by qiyeboy** [comment]
@Dang9527 @bihuchao 非常感谢你们提出的问题，当时只是演示join会阻塞主线程，确实考虑不周，容易造成误解
