### ISSUE TITLE
第七章：简单分布式爬虫

### ISSUE THREAD

**Issue by heqingbao** [qiyeboy/SpiderBook#49]
有个关键点没讲到：**multiprocessing.Queue**与**普通的Queue**的区别。

如果这里导入了普通的Queue，根本就无法跨进程通信。

而书中你所说的参考1.4.4节中服务进程的代码，1.4.4节中用的普通的Queue，但是后面操作的时候并不是直接用外面创建的普通Queue。

这里容易误导。

**Comment by qiyeboy** [comment]
Queue.Queue是进程内非阻塞队列，multiprocess.Queue是跨进程通信队列。多进程前者是各自私有，后者是各子进程共有。
参考1.4.4节中服务进程的代码，我的本意是参考注册网络的方式，不过你说的问题的确存在，确实是我语焉不详，下次印刷我会添加一个注意，非常感谢。
