### ISSUE TITLE
P144, 百度百科词条链接换成中文相对应字节编码形式了， 获取符合要求链接的正则表达式不可以用了

### ISSUE THREAD

**Issue by Judy0513** [qiyeboy/SpiderBook#5]

**Comment by qiyeboy** [comment]
这一个说的详细一些，给张图片示意一下

**Comment by Judy0513** [comment]
def _get_new_urls(self, page_url, soup):
links = soup.find_all('a', href = re.compile(r'/view/\d+\.htm'))

**Comment by qiyeboy** [comment]
看了一下这是由于百度词条的网页结构发生了改变，你可以用学过的正则表达式改写一下，这不属于代码中的错误。做爬虫就是这样，网页结构变化了，你也要会用学过的知识来应对

**Comment by qiyeboy** [comment]
我会更新的代码，不过相信你通过前面的学习，这里的代码也会自己修改的
