### ISSUE TITLE
请问关于第九章，爬取mtime时，引用到DynamicSpider这个模块，请问需要安装哪一个插件么？书中和网上未找到。谢谢！

### ISSUE THREAD

**Issue by BonnieTang** [qiyeboy/SpiderBook#66]
请问关于第九章，爬取mtime时，引用到DynamicSpider这个模块，请问需要安装哪一个插件么？

 SpiderBook/ch09/9_2_DynamicSpider/SpiderMan.py ：
 from DynamicSpider.DataOutput import DataOutput
from DynamicSpider.HtmlDownloader import HtmlDownloader

如上

**Comment by qiyeboy** [comment]
![image](https://user-images.githubusercontent.com/8142734/34340167-d3e2a1d4-e9b9-11e7-8796-6c246547cb8f.png)

**Comment by qiyeboy** [comment]
9_2_DynamicSpider前面的9_2_去掉即可

**Comment by qiyeboy** [comment]
@BonnieTang

**Comment by BonnieTang** [comment]
好哒 @qiyeboy  谢谢大神！
刚试了，修改引用，取消路径即可，这个几个文件都在一个包里呢。我还以为是引用了其他的插件包😓
from DataOutput import DataOutput
from HtmlDownloader import HtmlDownloader
