### ISSUE TITLE
SpiderMan.py运行时候提示

### ISSUE THREAD

**Issue by mm800805** [qiyeboy/SpiderBook#67]
整个代码都是一样的，还是提示如下
D:\Python3d5\python.exe D:\project\SPiderMan.py
D:\Python3d5\lib\site-packages\bs4\__init__.py:146: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
crawl failed

Process finished with exit code 0

**Comment by mm800805** [comment]
说明一下，我是py3.5环境

**Comment by MyLove1230** [comment]
把HtmlDownloader.py 里的from_encoding  去掉
