### ISSUE TITLE
麻烦作者看一下基础篇爬百度词条的代码，每次运行都是直接到百度百科：词条锁定中

### ISSUE THREAD

**Issue by shaodamao** [qiyeboy/SpiderBook#7]
麻烦作者再一下基础篇爬百度词条的代码，每次运行都是直接到百度百科：词条锁定中

**Comment by qiyeboy** [comment]
测试过，没有出现这个问题

**Comment by shaodamao** [comment]
win10 pycharm ，HtmlParser.py 里面加了这个几行代码
`        for link in links:
            # 提取href属性
            new_url = link['href']
            # 拼接成完整网址
            new_full_url = urlparse.urljoin(page_url, new_url)
            **print page_url
            print new_url
            print new_full_url**
            new_urls.add(new_full_url)
        return new_urls`

运行SpiderMan.py ，结果为：
C:\spider\venv\lib\site-packages\bs4\__init__.py:146: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
http://baike.baidu.com/view/284853.htm
/view/10812319.htm
http://baike.baidu.com/view/10812319.htm
已经抓取1个链接
http://baike.baidu.com/view/10812319.htm
/view/10812319.htm
http://baike.baidu.com/view/10812319.htm
已经抓取2个链接

Process finished with exit code 0

麻烦七夜再看一下，这是什么情况

**Comment by qiyeboy** [comment]
这是由于百度词条的网页结构发生了改变，你看一下勘误表
