### ISSUE TITLE
书中36页TCP函数混用问题

### ISSUE THREAD

**Issue by swjtucorn** [qiyeboy/SpiderBook#71]
UDP 客户端的创建和运行
#coding:utf-8
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
for data in [b'Hello', b'World']:
    # 发送数据:
    s.sendto(data, ('127.0.0.1', 9999))
    # 接收数据:
    print(s.recv(1024).decode('utf-8')) #此处是UDP客户端的接收数据处，但是用TCP的接收函数s.recv也运行成功了，这是否意味着两个函数可以混用
s.close()

**Comment by qiyeboy** [comment]
可以混用，但是接收到的数据格式不一样，因此不推荐
