### ISSUE TITLE
想请教下作者一些事

### ISSUE THREAD

**Issue by theratlesnake** [qiyeboy/SpiderBook#8]
我之前没学过python，想了解一下goagent的原理才找到这里的，但是看了下是循环渐进的教学，应该挺不错的，但是看了反馈，貌似书中错误挺多的，我现在购买好呢，还是等修订版噢？
还有，我以前看的Java教程，源码都是可以跑起来的，github上的源码能跑吗？（我懒，我都是先跑源码再对着书了解的，没源码的书更懒得看了）
最后，我看到goagent有打包exe程序，想问下作者书里有这方面的介绍吗？谢谢。

**Comment by qiyeboy** [comment]
goagent是一个代理程序，和本书的关系不大。本书是关于爬虫的。书中的内容比较多，确实有一些纰漏，希望大家谅解。代码会在github中一直更新，同时提供了大家反馈问题的渠道，代码我会努力保证能正常工作。

**Comment by theratlesnake** [comment]
其实我的意思是，我是顺着goagent，想学习一下python...
